/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ProximityMatch {
  id: number
  dist: number
}
export interface RouteStep {
  startId: number
  endId: number
  dist: number
}
export interface Country {
  coordinates: SphereCoordinates
  id: number
}
export interface SphereCoordinates {
  latitude: number
  longitude: number
}
export type JsMapQueryEngine = MapQueryEngine
export class MapQueryEngine {
  static withCountries(countries: Array<Country>): JsMapQueryEngine
  proximityQuery(centreId: number, radius: number): Promise<Array<ProximityMatch>>
  routeQuery(startId: number, endId: number, elasticity: number): Promise<Array<RouteStep>>
}
