version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/config.yaml"]
    volumes:
      - ./collector-config.yml:/etc/config.yaml
    ports:
      - "127.0.0.1:4317:4317"
    networks: [exporter]
    depends_on: [jaeger]

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "127.0.0.1:16686:16686"
    networks: [exporter]

networks:
  exporter:
