# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          helpers/.cargo-cache
          helpers/target/
        key: ${{ runner.os }}-cargo
    - name: Cache yarn dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          .yarn/cache
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Use Node.js 17
      uses: actions/setup-node@v2
      with:
        node-version: 17
        cache: 'yarn'
    - name: Install stable rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - run: yarn install
    - name: Build
      run: yarn run build
    - name: Lint
      run: yarn lint
    - name: Prettify
      run: yarn format
